version: '3.5'

services:
  ceramics_shape:
    container_name: ceramics_shape
    build:
      context: Docker/
      network: host
    ports: 
      - '8888:8888' #for jupyter notebook
    volumes:
      - ./:/home/Code/
      - /home/michael/Desktop/test:/home/michael/Desktop/test/
      - /home/michael/Desktop/binary masks/images/:/home/michael/Desktop/binary masks/images/
      - /home/michael/Desktop/binary masks/masks/:/home/michael/Desktop/binary masks/masks/
      - /home/michael/Downloads/miningshapes_cleaned/:/home/images/miningshapes_cleaned
      - /home/michael/Desktop/Binaries/:/home/images/Binaries
      #vscode extensions
      - ./vscode_remote/extensions/:/home/michael/.vscode-server/extensions/
      - ./vscode_remote/insiders/:/home/michael/.vscode-server-insiders/extensions/
      #vscode bash history
      - ./vscode_remote/bashhistory:/commandhistory
    working_dir: /home/Code
    user: 1000:1000
    tty: true

